# Generated by Django 4.1.4 on 2022-12-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_companies_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='status', to='crawler.status'),
        ),
    ]
