# Generated by Django 4.1.4 on 2022-12-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_companies_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='short_name',
            field=models.CharField(max_length=11),
        ),
    ]
