# Generated by Django 4.1.4 on 2022-12-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_companies_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
