# Generated by Django 4.1.4 on 2023-01-09 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crawler', '0006_alter_accountreport_options_alter_cities_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Adı')),
                ('color', models.CharField(max_length=25, verbose_name='Rengi(İngilizce reng)')),
            ],
            options={
                'verbose_name': 'Sözleşme Durumu',
                'verbose_name_plural': 'Sözleşme Durumları',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=255)),
                ('person_number', models.IntegerField(blank=True)),
                ('record_place', models.CharField(max_length=255, verbose_name='Çekim yeri')),
                ('whatsapp', models.IntegerField(blank=True)),
                ('mail', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Sözleşme tarihi')),
                ('record_date', models.DateTimeField(verbose_name='Çekim tarihi')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.companies', verbose_name='Firma unvanı')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.agreementstatus', verbose_name='Sözleşme durumu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
            },
        ),
    ]
