# Generated by Django 4.1.4 on 2023-01-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_agreementstatus_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='created_date',
            field=models.DateTimeField(verbose_name='Sözleşme tarihi'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.agreementstatus', verbose_name='Sözleşme durumu'),
        ),
    ]
