# Generated by Django 4.1.4 on 2023-01-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_alter_agreement_created_date_alter_agreement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sözleşme tarihi'),
        ),
    ]
