# Generated by Django 4.1.4 on 2023-01-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_alter_agreement_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='record_date',
            field=models.DateTimeField(blank=True, verbose_name='Çekim tarihi'),
        ),
    ]
