# Generated by Django 4.1.4 on 2023-01-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_alter_agreement_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.agreementstatus', verbose_name='Sözleşme durumu'),
        ),
    ]
