# Generated by Django 4.1.4 on 2023-01-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_alter_agreement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='record_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Çekim yeri'),
        ),
    ]
