# Generated by Django 4.1.4 on 2023-01-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_alter_agreement_record_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='person_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='person_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='record_place',
            field=models.CharField(max_length=255, null=True, verbose_name='Çekim yeri'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='whatsapp',
            field=models.IntegerField(null=True),
        ),
    ]
