# Generated by Django 4.1.4 on 2023-01-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_alter_agreement_mail_alter_agreement_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Kişi Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='personels_caount',
            field=models.IntegerField(null=True, verbose_name='Personel sayısı'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='site',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fount',
            name='link',
            field=models.CharField(max_length=255, null=True, verbose_name='Site adresi'),
        ),
        migrations.AlterField(
            model_name='fount',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Unvan'),
        ),
    ]
