# Generated by Django 4.1.4 on 2023-01-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0015_alter_companies_address_alter_companies_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
