# Generated by Django 4.1.4 on 2023-01-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0016_agreement_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='sent_date',
            field=models.DateTimeField(null=True, verbose_name='Gönderme tarihi'),
        ),
    ]
