# Generated by Django 4.1.4 on 2023-01-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0016_agreement_updated_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountReport',
        ),
    ]
