# Generated by Django 4.1.4 on 2023-01-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0017_delete_accountreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('user_type', models.CharField(max_length=25)),
                ('report_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Hesap raporu',
                'verbose_name_plural': 'Hesap raporları',
            },
        ),
    ]
