# Generated by Django 4.1.4 on 2023-01-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0017_agreement_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='sent_date',
        ),
    ]
