# Generated by Django 4.1.4 on 2023-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0018_remove_agreement_sent_remove_agreement_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
