# Generated by Django 4.1.4 on 2023-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0018_accountreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreport',
            name='report_date',
            field=models.DateField(),
        ),
    ]
