# Generated by Django 4.1.4 on 2023-01-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0019_alter_accountreport_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSearchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=25, verbose_name='Bölge')),
                ('word', models.CharField(max_length=25, verbose_name='Kelime')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.cities', verbose_name='İl')),
            ],
        ),
    ]
