# Generated by Django 4.1.4 on 2023-01-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0020_googlesearchreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreport',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
