# Generated by Django 4.1.4 on 2023-01-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0023_remove_companies_google_scrap_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='slug',
            field=models.SmallIntegerField(blank=True, verbose_name='Sitede yazılan İl kodu'),
        ),
    ]
