# Generated by Django 4.1.4 on 2023-01-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0024_alter_cities_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
