# Generated by Django 4.1.4 on 2023-03-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0027_permision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='person_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='whatsapp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='short_name',
            field=models.CharField(max_length=35, verbose_name='Firma unvanı(ilk 11 hanesi)'),
        ),
    ]
