# Generated by Django 4.1.4 on 2023-03-08 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crawler', '0028_alter_agreement_person_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azexport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='Kişi Adı Soyadı')),
                ('sector', models.CharField(max_length=255, null=True, verbose_name='Sektör')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Firma unvanı')),
                ('short_name', models.CharField(max_length=11, null=True, verbose_name='Firma unvanı(ilk 11 hanesi)')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Sabit numarası')),
                ('tel', models.CharField(max_length=30, null=True, verbose_name='Cep numarası')),
                ('website', models.CharField(max_length=255, null=True)),
                ('mail', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Adres')),
                ('social_media', models.CharField(max_length=255, null=True, verbose_name='Sosyal Medya')),
                ('personels_caount', models.BigIntegerField(null=True, verbose_name='Personel sayısı')),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reminder', models.DateTimeField(default=None, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.cities', verbose_name='İl')),
                ('fount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.fount', verbose_name='Data kaynağı')),
                ('last_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azexport_last_status', to='crawler.status')),
                ('status', models.ManyToManyField(blank=True, related_name='azexport_status', to='crawler.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'AzExport datası',
                'verbose_name_plural': 'AzExport dataları',
                'unique_together': {('short_name', 'phone')},
            },
        ),
    ]
