# Generated by Django 4.1.4 on 2023-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0029_azexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='azexport',
            name='link',
            field=models.CharField(max_length=300, null=True, verbose_name='bağlantı'),
        ),
    ]
