# Generated by Django 4.1.4 on 2023-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0030_azexport_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='azexport',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='azexport',
            name='full_name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Kişi Adı Soyadı'),
        ),
    ]
