# Generated by Django 4.1.4 on 2023-03-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0031_alter_azexport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azexport',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Kişi Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='azexport',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Firma unvanı'),
        ),
    ]
