# Generated by Django 4.1.4 on 2023-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0032_alter_azexport_full_name_alter_azexport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='azexport',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
