# Generated by Django 4.1.4 on 2023-03-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0034_alter_companies_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companies',
            unique_together={('short_name', 'phone')},
        ),
    ]
