# Generated by Django 4.1.4 on 2023-01-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0026_agreement_contract_minute_agreement_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='KJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, default='', max_length=250, verbose_name='Röportaj veren adı soyadı')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Ekranda gözükecek unvan')),
                ('instagram', models.CharField(blank=True, default='', max_length=50, verbose_name='İnstagram hesabı')),
                ('website', models.CharField(blank=True, default='', max_length=250, verbose_name='Web adresi')),
                ('tel', models.CharField(blank=True, default='', max_length=20, verbose_name='Tel no')),
                ('sponser', models.CharField(blank=True, default='', max_length=250, verbose_name='ُSponsorluk')),
                ('ad_banner', models.CharField(blank=True, default='', max_length=250, verbose_name='ُAlt bant reklam')),
                ('play_time_as_minuate', models.CharField(blank=True, default='', max_length=2, verbose_name='Yayın dakikasi')),
                ('agreement_price', models.CharField(blank=True, default='', max_length=250, verbose_name='Sözleşme Ücreti')),
                ('Paid_price', models.CharField(blank=True, default='', max_length=250)),
                ('note', models.TextField(blank=True, default='', verbose_name='Not')),
                ('is_played', models.BooleanField(default=False, verbose_name='Yayınlanma')),
                ('videos', models.BooleanField(default=False, verbose_name='Görseller')),
                ('kj_detials', models.BooleanField(default=False, verbose_name='Görseller')),
                ('banner', models.BooleanField(default=False, verbose_name='Afiş')),
                ('presentation', models.BooleanField(default=False, verbose_name='Sunum')),
                ('subtitle', models.BooleanField(default=False, verbose_name='Altyazı')),
                ('youtube', models.BooleanField(default=False, verbose_name='Youtube')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Firmaya gönderim')),
                ('play_date', models.DateTimeField(default=None, null=True, verbose_name='Yayın tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.agreement')),
            ],
            options={
                'verbose_name': 'Kj listesi',
                'verbose_name_plural': 'Kj listeleri',
            },
        ),
    ]
