# Generated by Django 4.1.4 on 2023-03-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0028_alter_agreement_person_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KJStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Adı')),
                ('color', models.CharField(max_length=25, verbose_name='Rengi(İngilizce reng)')),
            ],
            options={
                'verbose_name': 'KJ kurgu Durumu',
                'verbose_name_plural': 'KJ kurgu Durumları',
            },
        ),
        migrations.CreateModel(
            name='KJStatusAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Adı')),
                ('color', models.CharField(max_length=25, verbose_name='Rengi(İngilizce reng)')),
            ],
            options={
                'verbose_name': 'KJ muhasebe Durumu',
                'verbose_name_plural': 'KJ muhasebe Durumları',
            },
        ),
        migrations.CreateModel(
            name='KJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, default='', max_length=250, verbose_name='Röportaj veren adı soyadı')),
                ('nikname', models.CharField(blank=True, default='', max_length=250, verbose_name='Kişi unvanı')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Ekranda gözükecek unvan')),
                ('instagram', models.CharField(blank=True, default='', max_length=50, verbose_name='İnstagram hesabı')),
                ('website', models.CharField(blank=True, default='', max_length=250, verbose_name='Web adresi')),
                ('tel', models.CharField(blank=True, default='', max_length=20, verbose_name='Tel no')),
                ('sponser', models.CharField(blank=True, default='', max_length=250, verbose_name='ُSponsorluk')),
                ('ad_banner', models.CharField(blank=True, default='', max_length=250, verbose_name='ُAlt bant reklam')),
                ('play_time_as_minuate', models.CharField(blank=True, default='', max_length=2, verbose_name='Yayın dakikasi')),
                ('note', models.TextField(blank=True, default='', verbose_name='Not')),
                ('is_played', models.BooleanField(default=False, verbose_name='Yayınlanma')),
                ('videos', models.BooleanField(default=False, verbose_name='Görseller')),
                ('kj_detials', models.BooleanField(default=False, verbose_name='Görseller')),
                ('banner', models.BooleanField(default=False, verbose_name='Afiş')),
                ('presentation', models.TextField(default='', verbose_name='Sunum')),
                ('subtitle', models.BooleanField(default=False, verbose_name='Altyazı')),
                ('youtube', models.BooleanField(default=False, verbose_name='Youtube')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Firmaya gönderim')),
                ('montaj', models.BooleanField(default=False, verbose_name='Montaj')),
                ('play_date', models.DateField(default=None, null=True, verbose_name='Yayın tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.agreement')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kurgu.kjstatus')),
                ('status_accounting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kurgu.kjstatusaccounting')),
            ],
            options={
                'verbose_name': 'Kj listesi',
                'verbose_name_plural': 'Kj listeleri',
            },
        ),
    ]
