# Generated by Django 4.1.4 on 2023-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kj',
            name='montaj',
            field=models.BooleanField(default=False, verbose_name='Montaj'),
        ),
        migrations.AlterField(
            model_name='kj',
            name='play_date',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Yayın tarihi'),
        ),
    ]
