# Generated by Django 4.1.4 on 2023-03-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kj',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurgu.kjstatus'),
        ),
    ]
