# Generated by Django 4.1.4 on 2023-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0002_alter_kj_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kj',
            name='company',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Firma unvanı'),
        ),
    ]
