# Generated by Django 4.1.4 on 2023-03-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0003_alter_kj_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='kj',
            name='record_date',
            field=models.DateTimeField(null=True, verbose_name='Çekim tarihi'),
        ),
    ]
