# Generated by Django 4.1.4 on 2023-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0003_alter_kj_play_date_alter_kj_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='KJStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Adı')),
                ('color', models.CharField(max_length=25, verbose_name='Rengi(İngilizce reng)')),
            ],
            options={
                'verbose_name': 'KJ Durumu',
                'verbose_name_plural': 'KJ Durumları',
            },
        ),
    ]
