# Generated by Django 4.1.4 on 2023-01-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0004_kjstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kj',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kurgu.kjstatus'),
        ),
    ]
