# Generated by Django 4.1.4 on 2023-01-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0005_kj_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='KJAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Adı')),
                ('color', models.CharField(max_length=25, verbose_name='Rengi(İngilizce reng)')),
            ],
            options={
                'verbose_name': 'KJ muhasebe Durumu',
                'verbose_name_plural': 'KJ muhasebe Durumları',
            },
        ),
        migrations.AlterModelOptions(
            name='kjstatus',
            options={'verbose_name': 'KJ kurgu Durumu', 'verbose_name_plural': 'KJ kurgu Durumları'},
        ),
        migrations.AddField(
            model_name='kj',
            name='status_accounting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kurgu.kjaccounting'),
        ),
    ]
