# Generated by Django 4.1.4 on 2023-03-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0005_kj_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kj',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Tel no'),
        ),
    ]
