# Generated by Django 4.1.4 on 2023-01-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0006_kjaccounting_alter_kjstatus_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KJAccounting',
            new_name='KJStatusAccounting',
        ),
    ]
