# Generated by Django 4.1.4 on 2023-03-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0007_alter_kj_play_time_as_minuate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kj',
            name='presentation',
        ),
    ]
