# Generated by Django 4.1.4 on 2023-03-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0008_remove_kj_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kj',
            name='presentation',
            field=models.DateField(default=None, null=True, verbose_name='Sunum tarihi'),
        ),
    ]
