# Generated by Django 4.1.4 on 2023-02-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0010_alter_kj_play_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kj',
            name='play_date',
            field=models.DateField(default=None, null=True, verbose_name='Yayın tarihi'),
        ),
    ]
