# Generated by Django 4.1.4 on 2023-02-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0011_alter_kj_play_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kj',
            name='Paid_price',
        ),
        migrations.RemoveField(
            model_name='kj',
            name='agreement_price',
        ),
        migrations.AddField(
            model_name='kj',
            name='nikname',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Kişi unvanı'),
        ),
        migrations.AlterField(
            model_name='kj',
            name='status',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='kurgu.kjstatus'),
        ),
    ]
