# Generated by Django 4.1.4 on 2023-02-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0012_remove_kj_paid_price_remove_kj_agreement_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kj',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurgu.kjstatus'),
        ),
    ]
