# Generated by Django 4.1.4 on 2023-02-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurgu', '0014_alter_kj_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kj',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kurgu.kjstatus'),
        ),
    ]
